=== celinelouvet/lyontechhub.github.io/schema/community.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "image": { "type": "string" },
    "name": { "type": "string" },
    "shortDescription": { "type": "string" },
    "tags": {
      "type": "array",
      "items": [
        { "type": "string" }
      ],
      "uniqueItems": true
    },
    "patternsGoogleCalendar": {
      "type": "array",
      "items": [
        { "type": "string" }
      ],
      "minItems": 1,
      "uniqueItems": true
    },
    "socialLinks": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "icon": { "type": "string" },
            "tooltip": { "type": "string" },
            "url": { "type": "string" }
          },
          "required": [
            "icon",
            "tooltip",
            "url"
          ]
        }
      ],
      "uniqueItems": true
    },
    "slackChannels": {
      "type": "array",
      "items": [
        { "type": "string" }
      ],
      "uniqueItems": true
    }
  },
  "required": [
    "image",
    "name",
    "shortDescription",
    "tags",
    "socialLinks"
  ]
}

=== celinelouvet/lyontechhub.github.io/data/CafeDevOpsLyon.json
{
  "image": "CafeDevOpsLyon.png",
  "name": "Café DevOps Lyon",
  "shortDescription": "Echanges visant à progresser sur les aspects opérationnels cloud, déploiement continu et scalabilité des infrastructures.",
  "tags": [
    "Cloud",
    "Operation",
    "Infrastructure",
    "Déploiement continu",
    "Resilience"
  ],
  "patternsGoogleCalendar": [
    "Café DevOps Lyon",
    "CafeDevOpsLyon"
  ],
  "socialLinks": [
    {
      "url": "https://cafedevops.org"
    },
    {
      "url": "https://www.meetup.com/fr-FR/cafe-devops-lyon/"
    },
    {
      "url": "https://twitter.com/CafeDevOpsLyon"
    }
  ]
}

=== celinelouvet/lyontechhub.github.io/data/LYAUG.json
{
  "image": "LYAUG.png",
  "name": "Lyon Android User Group",
  "shortDescription": "Le Google Developer Group (GDG) Lyon Android, alias #LYAUG est une association visant à regrouper les professionnels et les développeurs Android/Google de Lyon et de la région Rhône-Alpes lors de différents évènements.",
  "tags": [
    "Android",
    "Google"
  ],
  "patternsGoogleCalendar": [
    "Lyaug",
    "GDG"
  ],
  "socialLinks": [
    {
      "icon": "fab fa-meetup",
      "tooltip": "Meetup",
      "url": "https://www.meetup.com/Lyon-Android-User-Group-LYAUG/"
    },
    {
      "icon": "fab fa-twitter",
      "tooltip": "Twitter",
      "url": "https://twitter.com/LyonAndroidUG"
    }
  ]
}

=== celinelouvet/lyontechhub.github.io/data/LyonDataScience.json
{
  "image": "LyonDataScience.png",
  "name": "Lyon Data Science",
  "shortDescription": "Communauté d'échange et apprentissage autour des Data Science et machine learning à Lyon",
  "tags": [
    "Elasticsearch"
  ],
  "patternsGoogleCalendar": [
    "Lyon Data Science",
    "LyonDataScience"
  ],
  "socialLinks": [
    {
      "icon": "fas fa-link",
      "tooltip": "Web site",
      "url": "http://www.lyondata.science"
    },
    {
      "icon": "fab fa-twitter",
      "tooltip": "Twitter",
      "url": "https://twitter.com/LyonDataScience"
    },
    {
      "icon": "fab fa-facebook",
      "tooltip": "Facebook",
      "url": "https://www.facebook.com/pages/Lyondatascience/503525249798412?ref=tn_tnmn"
    },
    {
      "icon": "fab fa-github",
      "tooltip": "Git Hub Organization",
      "url": "https://github.com/lyondatascience"
    }
  ]
}

=== celinelouvet/lyontechhub.github.io/data/MUGLyon.json
{
  "image": "MUGLyon.png",
  "name": "MUG (Microsoft User Group) Lyon",
  "shortDescription": "Le MUG Lyon regroupe les passionnés des technologies Microsoft et affiliées. Un événement par mois est organisé le dernier jeudi de chaque mois soit sur des technos de la plateforme Microsoft (de l'éditeur ou de la communauté) ou sur des pratiques ou des outils.",
  "tags": [
    "Microsoft",
    "pratiques",
    "outils",
    ".NET",
    "C#",
    "JavaScript"
  ],
  "patternsGoogleCalendar": [
    "MUG",
    "MTGLyon"
  ],
  "socialLinks": [
    {
      "url": "http://muglyon.github.io/"
    },
    {
      "url": "https://www.meetup.com/fr-FR/MUGLyon/"
    },
    {
      "url": "https://www.twitter.com/muglyon"
    },
    {
      "url": "https://www.linkedin.com/groups/MUG-Lyon-4302523"
    },
    {
      "url": "https://www.github.com/muglyon"
    }
  ],
  "slackChannels": [
    "#muglyon"
  ]
}

=== celinelouvet/lyontechhub.github.io/data/AFSYSfPots.json
{
  "image": "AFSYSfPots.png",
  "name": "AFSY SfPots",
  "shortDescription": "L'AFSY organise les SfPots, des apéros décontractés autour du framework PHP Symfony",
  "tags": [
    "PHP",
    "Symfony",
    "AFSY-SfPots"
  ],
  "socialLinks": [
    {
      "url": "https://www.meetup.com/afsy-sfpot/"
    }
  ]
}

=== celinelouvet/lyontechhub.github.io/data/MTGLyon.json
{
  "image": "MUGLyon.png",
  "name": "MTG Lyon",
  "shortDescription": "Le MTG Lyon (anciennement MUG Lyon) regroupe les passionnés des technologies Microsoft et affiliées. Un événement par mois est organisé le dernier jeudi de chaque mois soit sur des technos de la plateforme Microsoft (de l'éditeur ou de la communauté) ou sur des pratiques ou des outils.",
  "tags": [
    "Microsoft",
    "MUG",
    "pratiques",
    "outils",
    ".NET",
    "C#",
    "JavaScript"
  ],
  "patternsGoogleCalendar": [
    "MUG",
    "MTGLyon"
  ],
  "socialLinks": [
    {
      "url": "http://muglyon.github.io/"
    },
    {
      "url": "https://www.meetup.com/fr-FR/mtglyon/"
    },
    {
      "url": "https://www.twitter.com/muglyon"
    },
    {
      "url": "https://www.linkedin.com/groups/MUG-Lyon-4302523"
    },
    {
      "url": "https://www.github.com/muglyon"
    }
  ],
  "slackChannels": [
    "#muglyon"
  ]
}

=== celinelouvet/lyontechhub.github.io/data/hckrs.json
{
  "image": "hckrs.png",
  "name": "hckrs.io",
  "shortDescription": "Communaut√© locale de bidouilleurs.",
  "tags": [
    "Developpement",
    "Design",
    "Hardware",
    "Growth hacking",
    "Life Hacking"
  ],
  "socialLinks": [
    {
      "icon": "link",
      "tooltip": "Web site",
      "url": "http://hckrs.io/+/-__----"
    },
    {
      "icon": "twitter",
      "tooltip": "Twitter",
      "url": "http://www.twitter.com/hckrslyon"
    },
    {
      "icon": "github",
      "tooltip": "Git Hub Organization",
      "url": "https://github.com/hckrs/hckrs.io"
    }
  ],
  "patternsGoogleCalendar": []
}

=== celinelouvet/lyontechhub.github.io/data/LyonJS.json
{
  "image": "LyonJS.png",
  "name": "LyonJS",
  "shortDescription": "LyonJS ce sont des talks long format sur un sujet hype du moment, des lightnings talks pour vous faire découvrir autre chose, le tout suivi d'un apéro pour se rencontrer et discuter tous ensemble.",
  "tags": [
    "JavaScript",
    "JS",
    "Angular",
    "Node.JS"
  ],
  "patternsGoogleCalendar": [
    "LyonJS"
  ],
  "socialLinks": [
    {
      "url": "http://lyonjs.org/"
    },
    {
      "url": "https://twitter.com/LyonJS"
    },
    {
      "url": "https://github.com/lyonjs"
    },
    {
      "url": "https://www.youtube.com/channel/UCGTVc5PnIgAUoA2D2_6nJLg"
    }
  ]
}
