=== celinelouvet/lyontechhub.github.io/schema/community.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "image": { "type": "string" },
    "name": { "type": "string" },
    "shortDescription": { "type": "string" },
    "tags": {
      "type": "array",
      "items": [
        { "type": "string" }
      ],
      "uniqueItems": true
    },
    "patternsGoogleCalendar": {
      "type": "array",
      "items": [
        { "type": "string" }
      ],
      "minItems": 1,
      "uniqueItems": true
    },
    "socialLinks": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "icon": { "type": "string" },
            "tooltip": { "type": "string" },
            "url": { "type": "string" }
          },
          "required": [
            "icon",
            "tooltip",
            "url"
          ]
        }
      ],
      "uniqueItems": true
    },
    "slackChannels": {
      "type": "array",
      "items": [
        { "type": "string" }
      ],
      "uniqueItems": true
    }
  },
  "required": [
    "image",
    "name",
    "shortDescription",
    "tags",
    "socialLinks"
  ]
}

=== celinelouvet/lyontechhub.github.io/data/LaboratoireOuvertLyonnais.json
{
  "image": "LaboratoireOuvertLyonnais.svg",
  "name": "Laboratoire Ouvert Lyonnais",
  "shortDescription": "Le Laboratoire Ouvert Lyonnais est un hackerspace proposant un espace pour sa communauté afin de réaliser et accompagner des projets, apprendre et partager des connaissances ou des technologies (peu importe le domaine), le tous dans la joie et la bonne humeur",
  "tags": [
    "Open source",
    "Électronique",
    "Informatique",
    "Hacking",
    "Ethical Hacker",
    "DIY",
    "Projets",
    "Hackerspace",
    "Bidouilles",
    "Apprendre",
    "Échange",
    "Partage",
    "Rencontre"
  ],
  "patternsGoogleCalendar": [
    "LaboratoireOuvertLyonnais"
  ],
  "socialLinks": [
    {
      "icon": "fas fa-link",
      "tooltip": "Web site",
      "url": "https://labolyon.fr"
    },
    {
      "icon": "fab fa-meetup",
      "tooltip": "Groupe Meetup",
      "url": "http://www.meetup.com/fr/Laboratoire-Ouvert-Lyonnais/"
    },
    {
      "icon": "fas fa-code-branch",
      "tooltip": "Git Forge",
      "url": "https://git.labolyon.fr/"
    },
    {
      "icon": "fab fa-weixin",
      "tooltip": "IRC",
      "url": "irc://irc.geeknode.org/labolyon"
    },
    {
      "icon": "fab fa-twitter",
      "tooltip": "Twitter",
      "url": "https://twitter.com/LaboLyon"
    }
  ]
}

=== celinelouvet/lyontechhub.github.io/data/HumanTalks.json
{
  "image": "HumanTalks.png",
  "name": "Human Talks Lyon",
  "shortDescription": "Des talks de 10 minutes accessibles à tous, pour découvrir des sujets techs variés et partager ses passions. Tous les 2nds mardi du mois partout en France et à Lyon en particulier !",
  "tags": [],
  "patternsGoogleCalendar": [
    "Human Talks",
    "HumanTalks"
  ],
  "socialLinks": [
    {
      "url": "http://humantalks.com/cities/lyon"
    },
    {
      "url": "https://www.meetup.com/HumanTalks-Lyon/"
    },
    {
      "url": "https://www.twitter.com/HumanTalksLyon"
    }
  ]
}

=== celinelouvet/lyontechhub.github.io/data/AFPy.json
{
  "image": "AFPy.png",
  "name": "Rencontres Python",
  "shortDescription": "Une rencontre Python est un moment où les développeurs et développeuses se retrouvent autour d'un verre et d'une présentation pour échanger autour de ce langage. L'accès est gratuit et ouvert à tous. Cet événement est organisé par l'Association Francophone Python (AFPY).",
  "tags": [
    "Python",
    "DevOps",
    "Scientific",
    "Web"
  ],
  "patternsGoogleCalendar": [
    "Python",
    "AFPY"
  ],
  "socialLinks": [
    {
      "url": "http://www.afpy.org"
    },
    {
      "url": "https://www.meetup.com/fr/Python-AFPY-Lyon/"
    },
    {
      "url": "https://twitter.com/python_lyon"
    },
    {
      "url": "https://www.github.com/AFPy"
    }
  ]
}

=== celinelouvet/lyontechhub.github.io/data/LyonDataViz.json
{
  "image": "LyonDataViz.png",
  "name": "Lyon DataViz",
  "shortDescription": "Echange de pratiques, id√©es et outils autour de la Data Visualization",
  "tags": [
    "Dataviz",
    "D3.js",
    "JavaScript",
    "Visualisation",
    "Visual Analytics",
    "Design"
  ],
  "patternsGoogleCalendar": [
    "Lyon DataViz",
    "LyonDataViz"
  ],
  "socialLinks": [
    {
      "icon": "fas fa-link",
      "tooltip": "Web site",
      "url": "http://www.meetup.com/Lyon-Dataviz/"
    },
    {
      "icon": "fab fa-twitter",
      "tooltip": "Twitter",
      "url": "https://twitter.com/LyonDataViz"
    },
    {
      "icon": "fab fa-github",
      "tooltip": "Git Hub Organization",
      "url": "https://github.com/LyonDataViz/"
    }
  ]
}

=== celinelouvet/lyontechhub.github.io/data/IALyon.json
{
  "image": "MeetupIALyon.png",
  "name": "Meetup Intelligence Artificielle Lyon",
  "shortDescription": "Le but est de rassembler un réseau de passionnés, de mettre en commun les compétences afin de développer des projets (par exemple dans le traitement des datas, ou dans la robotique) et de produire une réflexion sur ce sujet complexe qu'est l'Intelligence Artificielle",
  "tags": [
    "meetup",
    "intelligence artificielle",
    "networking",
    "informatique",
    "Usages",
    "Design",
    "innovation",
    "Big Data",
    "Philosophie",
    "entrepreneuriat",
    "maker"
  ],
  "patternsGoogleCalendar": [
    "Meetup Intelligence Artificielle Lyon",
    "IALyon"
  ],
  "socialLinks": [
    {
      "url": "https://www.meetup.com/fr-FR/ialyon/"
    }
  ]
}

=== celinelouvet/lyontechhub.github.io/data/ITWomenTalk.json
{
  "name": "IT WOMEN TALK",
  "image": "ITWomenTalk.png",
  "shortDescription": "Organisé par Yeeso. Met en avant l’expertise féminine et le réseautage professionnel. 100% conférencières avec un public mixte avec 2 sujets par événement, un sujet tech (dev, cloud, data etc.) et un sujet social tech (sensibilisation, inclusion, etc.).",
  "tags": [
    "Yeeso",
    "ITWomen",
    "Tech",
    "Social tech",
    "Conférencières",
    "Mixité",
    "Mentorat"
  ],
  "patternsGoogleCalendar": ["ITWomen"],
  "socialLinks": [
    {
      "url": "https://www.meetup.com/fr-fr/it-woman-by-yeeso/"
    },
    {
      "url": "https://yeeso.fr"
    },
    {
      "url": "https://www.linkedin.com/company/it-woman"
    }
  ]
}

=== celinelouvet/lyontechhub.github.io/data/LyonGameDev.json
{
  "image": "lyongamedev.png",
  "name": "LyonGameDev",
  "shortDescription": "Les brasseurs du jeu-vidéo lyonnais. Bières, pitchs et gros pixels... Pour l'instant c'est avant tout une rencontre mensuelle, mais cela peut devenir bien plus encore !",
  "tags": [
    "GameDev",
    "Jeu vidéo",
    "Game",
    "Video Game"
  ],
  "socialLinks": [
    {
      "url": "http://lyongamedev.pro"
    },
    {
      "url": "https://twitter.com/lyon_dev"
    },
    {
      "url": "https://www.linkedin.com/company/lyongamedev/?viewAsMember=true"
    },
    {
      "url": "https://www.facebook.com/LyonGameDevPage/"
    },
    {
      "url": "https://github.com/lyongamedev"
    }
  ]
}

=== celinelouvet/lyontechhub.github.io/data/TheNEO.json
{
  "image": "TheNEO.png",
  "name": "The Next Entreprise Organisation",
  "shortDescription": "Les nouvelles formes d'organisations",
  "tags": [
    "Agile",
    "Lean",
    "Organisations liber√©es"
  ],
  "patternsGoogleCalendar": [
    "TheNEO"
  ],
  "socialLinks": [
    {
      "url": "https://www.meetup.com/fr-FR/theneo/"
    }
  ]
}
