=== celinelouvet/lyontechhub.github.io/schema/community.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "image": { "type": "string" },
    "name": { "type": "string" },
    "shortDescription": { "type": "string" },
    "tags": {
      "type": "array",
      "items": [
        { "type": "string" }
      ],
      "uniqueItems": true
    },
    "patternsGoogleCalendar": {
      "type": "array",
      "items": [
        { "type": "string" }
      ],
      "minItems": 1,
      "uniqueItems": true
    },
    "socialLinks": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "icon": { "type": "string" },
            "tooltip": { "type": "string" },
            "url": { "type": "string" }
          },
          "required": [
            "icon",
            "tooltip",
            "url"
          ]
        }
      ],
      "uniqueItems": true
    },
    "slackChannels": {
      "type": "array",
      "items": [
        { "type": "string" }
      ],
      "uniqueItems": true
    }
  },
  "required": [
    "image",
    "name",
    "shortDescription",
    "tags",
    "socialLinks"
  ]
}

=== celinelouvet/lyontechhub.github.io/data/Aldil.json
{
  "image": "Aldil.png",
  "name": "Aldil",
  "shortDescription": "Association Lyonnaise pour le DÃ©veloppement de l'Informatique Libre",
  "tags": [
    "Libre",
    "Opensource"
  ],
  "patternsGoogleCalendar": [
    "Aldil"
  ],
  "socialLinks": [
    {
      "url": "http://aldil.org"
    },
    {
      "url": "https://twitter.com/aldil_lyon"
    }
  ]
}

=== celinelouvet/lyontechhub.github.io/data/LAWS.json
{
  "image": "LAWS.png",
  "name": "LAWS - Lyon Amazon Web Services UG",
  "shortDescription": "Groupe officiel Amazon Web Services de la région Lyonnaise. Organisation de Meetup autour des services AWS, retours d'expériences, live coding, ...",
  "patternsGoogleCalendar": [
    "LAWS"
  ],
  "tags": [
    "AWS",
    "EC2",
    "Cloud Computing",
    "Information Technology",
    "Big Data",
    "High Scalability Computing",
    "Data Analytics",
    "IaaS (Infrastructure as a Service)",
    "S3",
    "RDS",
    "Redshift"
  ],
  "socialLinks": [
    {
      "url": "https://www.meetup.com/LAWS-Lyon-Amazon-Web-Services-User-Group/"
    }
  ]
}

=== celinelouvet/lyontechhub.github.io/data/MaxSessionsLyon.json
{
  "image": "MaxSessionsLyon.png",
  "name": "Max Sessions Lyon",
  "shortDescription": "Nous sommes un collectif passionné, dédié à l'excellence dans le développement, le software craftsmanship, la technologie et l'innovation en management.\n Notre mission est de créer un espace où professionnels, novices, et curieux peuvent se rencontrer, échanger, et grandir ensemble.\n Max Session vise à devenir un carrefour d'échange et d'apprentissage pour tous ceux qui partagent une passion pour la technologie et l'innovation en management.\n Notre but est de construire une communauté solide et engagée, capable de pousser les limites de ce que nous savons et de ce que nous pouvons faire ensemble.\n Que vous soyez développeur, chef de projet, designer UX/UI, entrepreneur tech, ou simplement intéressé par le monde du développement et de l'innovation managériale, vous trouverez votre place parmi nous.",
  "tags": [
    "Craftsmanship",
    "Software Engineering",
    "Development",
    "Management",
    "DevOps",
    "Cloud",
    "Product",
    "Design",
    "Agile",
    "Architecture"
  ],
  "patternsGoogleCalendar": ["Max Sessions Lyon", "maxsession-lyon"],
  "socialLinks": [
    {
      "icon": "fas fa-link",
      "tooltip": "Blog",
      "url": "https://blog.maxds.fr/"
    },
    {
      "icon": "fas fa-calendar",
      "tooltip": "Meetup",
      "url": "https://www.meetup.com/maxsession-lyon"
    },
    {
      "icon": "fab fa-youtube",
      "tooltip": "Youtube",
      "url": "https://www.youtube.com/channel/UC4oL-CO7XCLgHZCqisxOi6w"
    }
  ],
  "slackChannels": ["#maxsession_meetup"]
}

=== celinelouvet/lyontechhub.github.io/data/DockerLyon.json
{
  "image": "DockerLyon.png",
  "name": "Docker Lyon",
  "shortDescription": "Les meetups Docker Lyon sont l'occasion de se retrouver et d'echanger autour de Docker, la technologie de containerisation",
  "tags": [
    "Docker"
  ],
  "patternsGoogleCalendar": [
    "DockerLyon"
  ],
  "socialLinks": [
    {
      "icon": "fas fa-link",
      "tooltip": "Web site",
      "url": "http://www.meetup.com/Docker-Lyon/"
    }
  ]
}

=== celinelouvet/lyontechhub.github.io/data/SoftwareCraftsmanshipLyon.json
{
  "image": "SoftwareCraftsmanshipLyon.png",
  "name": "Software Craftsmanship Lyon",
  "shortDescription": "La communauté Software Craftsmanship Lyon réunit les développeurs, sans sexisme, élitisme ni langage ou techno obligatoire.",
  "tags": [
    "Craftsmanship",
    "artisan",
    "Coding Dojo"
  ],
  "patternsGoogleCalendar": [
    "Software Craftsmanship Lyon",
    "SWCrafters"
  ],
  "socialLinks": [
    {
      "icon": "fas fa-link",
      "tooltip": "Web site",
      "url": "http://www.meetup.com/fr/Software-Craftsmanship-Lyon/"
    },
    {
      "icon": "fas fa-calendar",
      "tooltip": "Meetup",
      "url": "http://www.meetup.com/fr/Software-Craftsmanship-Lyon/"
    },
    {
      "icon": "fab fa-twitter",
      "tooltip": "Twitter",
      "url": "http://www.twitter.com/swcraftlyon"
    }
  ],
  "slackChannels": [
    "#swcrafts_meetup"
  ]
}

=== celinelouvet/lyontechhub.github.io/data/GolangLyon.json
{
  "image": "GolangLyon.png",
  "name": "Golang Lyon",
  "shortDescription": "Ce groupe s'adresse à toute personne s'intéressant de près ou de loin au langage Go : curieux, débutants ou personnes expérimentées !",
  "tags": [
    "Go",
    "Golang"
  ],
  "patternsGoogleCalendar": [
    "Golang Lyon",
    "GolangLyon"
  ],
  "socialLinks": [
    {
      "icon": "fas fa-link",
      "tooltip": "Web site",
      "url": "http://www.meetup.com/Golang-Lyon/"
    },
    {
      "icon": "fab fa-twitter",
      "tooltip": "Twitter",
      "url": "https://twitter.com/GolangLyon"
    }
  ]
}

=== celinelouvet/lyontechhub.github.io/data/IppEventsLyon.json
{
  "image": "IppEventsLyon.svg",
  "name": "IppEvents Lyon",
  "shortDescription": "Chez Ippon Technologies, on aime partager et échanger autour des nouvelles technologies.\nNous organisons des évènements et invitons régulièrement des experts afin de découvrir et comprendre les dernières innovations.\n\nRejoignez-nous à l'occasion de nos IppEvents :)",
  "tags": [
    "Craftsmanship",
    "Software Engineering",
    "DATA",
    "DevOps",
    "Cloud",
    "Product",
    "Design",
    "Agile",
    "Architecture"
  ],
  "patternsGoogleCalendar": [
    "IppEvents"
  ],
  "socialLinks": [
    {
      "icon": "fas fa-link",
      "tooltip": "Blog",
      "url": "https://blog.ippon.fr/"
    },
    {
      "icon": "fas fa-calendar",
      "tooltip": "Meetup",
      "url": "https://www.meetup.com/fr-FR/ippevents-lyon/"
    },
    {
      "icon": "fab fa-twitch",
      "tooltip": "Twitch",
      "url": "https://www.twitch.tv/ippontech"
    },
    {
      "icon": "fab fa-youtube",
      "tooltip": "Youtube",
      "url": "https://www.youtube.com/@ippontechtv"
    }
  ],
  "slackChannels": [
    "#ippevents"
  ]
}

=== celinelouvet/lyontechhub.github.io/data/AFUPLyon.json
{
  "image": "AFUPLyon.png",
  "name": "AFUP Lyon / Apéros PHP",
  "shortDescription": "L'AFUP Lyon organise des apéros, ateliers, rendez-vous autour des dernières avancées du langage PHP.",
  "tags": [
    "PHP",
    "AFUP",
    "Symfony",
    "Laravel"
  ],
  "patternsGoogleCalendar": [
    "Apéro PHP",
    "AFUP"
  ],
  "socialLinks": [
    {
      "url": "https://www.meetup.com/fr-FR/afup-lyon-php/"
    },
    {
      "url": "https://twitter.com/AFUP_lyon"
    },
    {
      "url": "https://www.linkedin.com/company/afup-lyon/"
    },
    {
      "url": "https://www.github.com/afup"
    }
  ]
}
